-- ==============================================================================
-- BUSY BEES: FIX FORM SCHEMAS MIGRATION
-- ==============================================================================
-- INSTRUCTIONS: Copy all of this text and run it in your Supabase SQL Editor.
-- This will add the missing JSONB and TEXT columns needed by the forms pages 
-- that were present in json-server but missing in the original migration script.
-- ==============================================================================

-- 1. BASELINE SHEET FIXES
ALTER TABLE IF EXISTS public."academic_baselines" ADD COLUMN IF NOT EXISTS "clientName" TEXT;
ALTER TABLE IF EXISTS public."academic_baselines" ADD COLUMN IF NOT EXISTS "program" TEXT;
ALTER TABLE IF EXISTS public."academic_baselines" ADD COLUMN IF NOT EXISTS "rows" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public."academic_baselines" ADD COLUMN IF NOT EXISTS "sessions" JSONB DEFAULT '[]'::jsonb;

-- 2. MASS TRIAL FIXES
ALTER TABLE IF EXISTS public."mass_trials" ADD COLUMN IF NOT EXISTS "clientName" TEXT;
ALTER TABLE IF EXISTS public."mass_trials" ADD COLUMN IF NOT EXISTS "program" TEXT;
ALTER TABLE IF EXISTS public."mass_trials" ADD COLUMN IF NOT EXISTS "targets" JSONB DEFAULT '[]'::jsonb;
ALTER TABLE IF EXISTS public."mass_trials" ADD COLUMN IF NOT EXISTS "dailyLogs" JSONB DEFAULT '[]'::jsonb;

-- 3. DAILY ROUTINES FIX (Missing table)
CREATE TABLE IF NOT EXISTS public."daily_routines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" TEXT,
    "clientName" TEXT,
    "routineName" TEXT,
    "config" JSONB DEFAULT '[]'::jsonb,
    "dailyLogs" JSONB DEFAULT '[]'::jsonb,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 4. TRANSACTION SHEETS FIX (Missing table)
CREATE TABLE IF NOT EXISTS public."transaction_sheets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" TEXT,
    "clientName" TEXT,
    "employeeId" TEXT,
    "employeeName" TEXT,
    "date" TEXT,
    "cellPhoneLocation" TEXT,
    "program" TEXT,
    "locations" JSONB DEFAULT '[]'::jsonb,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- Note: Depending on your RLS settings, they should be disabled for these or policies created.
