-- ==============================================================================
-- BUSY BEES: FINAL SUPABASE MIGRATION SCRIPT
-- ==============================================================================
-- INSTRUCTIONS: Copy all of this text and run it in your Supabase SQL Editor.
-- This will create all the missing tables that were previously only in json-server.
-- It uses "IF NOT EXISTS" so it will NOT overwrite your existing tables or data!
-- ==============================================================================

-- 1. SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public."sessions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sessionId" TEXT,
    "userId" TEXT,
    "workerName" TEXT,
    "employeeName" TEXT,
    "employeeId" TEXT,
    "clientId" TEXT,
    "clientName" TEXT,
    "clientStatus" TEXT,
    "serviceType" TEXT,
    "startTime" TIMESTAMPTZ,
    "endTime" TIMESTAMPTZ,
    "durationSeconds" NUMERIC DEFAULT 0,
    "status" TEXT DEFAULT 'active',
    "notes" TEXT,
    "documents" JSONB DEFAULT '[]'::jsonb,
    "route" JSONB DEFAULT '[]'::jsonb,
    "signature" TEXT,
    "signedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 2. DOCUMENTS TABLE
CREATE TABLE IF NOT EXISTS public."documents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT,
    "url" TEXT,
    "size" TEXT,
    "type" TEXT,
    "uploadedBy" TEXT,
    "uploadedAt" TIMESTAMPTZ DEFAULT now(),
    "clientId" TEXT,
    "metadata" JSONB DEFAULT '{}'::jsonb
);

-- 3. SCHEDULE TABLE
CREATE TABLE IF NOT EXISTS public."schedule" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeId" TEXT,
    "clientId" TEXT,
    "serviceId" TEXT,
    "date" DATE,
    "startTime" TIME,
    "endTime" TIME,
    "status" TEXT DEFAULT 'scheduled',
    "notes" TEXT,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 4. ACADEMIC BASELINES TABLE
CREATE TABLE IF NOT EXISTS public."academic_baselines" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" TEXT,
    "programId" TEXT,
    "baselineData" JSONB DEFAULT '{}'::jsonb,
    "evaluator" TEXT,
    "date" DATE,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 5. PROBES TABLE
CREATE TABLE IF NOT EXISTS public."probes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" TEXT,
    "targetId" TEXT,
    "score" NUMERIC,
    "date" DATE,
    "notes" TEXT,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 6. AVAILABILITY TABLE
CREATE TABLE IF NOT EXISTS public."availability" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employeeId" TEXT,
    "dayOfWeek" TEXT,
    "startTime" TIME,
    "endTime" TIME,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 7. PROGRAM MASTERY TABLE
CREATE TABLE IF NOT EXISTS public."program_mastery" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" TEXT,
    "programId" TEXT,
    "status" TEXT,
    "dateMastered" DATE,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 8. MASS TRIALS TABLE
CREATE TABLE IF NOT EXISTS public."mass_trials" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" TEXT,
    "programId" TEXT,
    "trialData" JSONB DEFAULT '[]'::jsonb,
    "date" DATE,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- 9. PROVIDERS TABLE (In case it was missed in the original init)
CREATE TABLE IF NOT EXISTS public."providers" (
    "id" TEXT PRIMARY KEY,
    "name" TEXT,
    "color" TEXT,
    "textColor" TEXT
);

-- Ensure RLS is disabled temporarily for rapid testing (if not already disabled)
-- (Users can enable Row Level Security inside the Supabase dashboard later)
