import { createClient } from '@supabase/supabase-js'
import fs from 'fs'

const env = fs.readFileSync('.env.local', 'utf8').split('\n').reduce((acc, line) => {
    const [k, v] = line.split('=')
    if (k && v) acc[k.trim()] = v.trim().replace(/^"|"$/g, '')
    return acc
}, {})

const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY)

async function run() {
    const sql = `
        ALTER TABLE IF EXISTS public.academic_baselines ADD COLUMN IF NOT EXISTS "clientName" TEXT;
        ALTER TABLE IF EXISTS public.academic_baselines ADD COLUMN IF NOT EXISTS "program" TEXT;
        ALTER TABLE IF EXISTS public.academic_baselines ADD COLUMN IF NOT EXISTS "rows" JSONB DEFAULT '[]'::jsonb;
        ALTER TABLE IF EXISTS public.academic_baselines ADD COLUMN IF NOT EXISTS "sessions" JSONB DEFAULT '[]'::jsonb;

        ALTER TABLE IF EXISTS public.mass_trials ADD COLUMN IF NOT EXISTS "clientName" TEXT;
        ALTER TABLE IF EXISTS public.mass_trials ADD COLUMN IF NOT EXISTS "program" TEXT;
        ALTER TABLE IF EXISTS public.mass_trials ADD COLUMN IF NOT EXISTS "targets" JSONB DEFAULT '[]'::jsonb;
        ALTER TABLE IF EXISTS public.mass_trials ADD COLUMN IF NOT EXISTS "dailyLogs" JSONB DEFAULT '[]'::jsonb;
        
        CREATE TABLE IF NOT EXISTS public."daily_routines" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "clientId" TEXT,
            "clientName" TEXT,
            "routineName" TEXT,
            "config" JSONB DEFAULT '[]'::jsonb,
            "dailyLogs" JSONB DEFAULT '[]'::jsonb,
            "createdAt" TIMESTAMPTZ DEFAULT now()
        );
        
        CREATE TABLE IF NOT EXISTS public."transaction_sheets" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "clientId" TEXT,
            "clientName" TEXT,
            "employeeId" TEXT,
            "employeeName" TEXT,
            "date" TEXT,
            "cellPhoneLocation" TEXT,
            "program" TEXT,
            "locations" JSONB DEFAULT '[]'::jsonb,
            "createdAt" TIMESTAMPTZ DEFAULT now()
        );
    `
    // Supabase JS library doesn't easily allow raw SQL execution through the anon key over REST API,
    // so we'll just log this and I will inform the user.
    console.log(sql);
}
run()
