// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/clients" | "/clients/[id]" | "/employees" | "/employees/[id]" | "/employees/roles" | "/forms" | "/forms/baseline-sheet" | "/forms/baseline-sheet/[id]" | "/forms/baseline-sheet/data-table" | "/forms/daily-routines" | "/forms/daily-routines/[id]" | "/forms/daily-routines/data-table" | "/forms/mass-trial" | "/forms/mass-trial/[id]" | "/forms/mass-trial/data-table" | "/forms/transaction-sheet" | "/forms/transaction-sheet/[id]" | "/forms/transaction-sheet/[id]/view" | "/forms/transaction-sheet/data-table" | "/services/client-services" | "/services/list" | "/session-summary"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/clients": {}
  "/clients/[id]": { "id": string; }
  "/employees": {}
  "/employees/[id]": { "id": string; }
  "/employees/roles": {}
  "/forms": {}
  "/forms/baseline-sheet": {}
  "/forms/baseline-sheet/[id]": { "id": string; }
  "/forms/baseline-sheet/data-table": {}
  "/forms/daily-routines": {}
  "/forms/daily-routines/[id]": { "id": string; }
  "/forms/daily-routines/data-table": {}
  "/forms/mass-trial": {}
  "/forms/mass-trial/[id]": { "id": string; }
  "/forms/mass-trial/data-table": {}
  "/forms/transaction-sheet": {}
  "/forms/transaction-sheet/[id]": { "id": string; }
  "/forms/transaction-sheet/[id]/view": { "id": string; }
  "/forms/transaction-sheet/data-table": {}
  "/services/client-services": {}
  "/services/list": {}
  "/session-summary": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
