// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clients">> = Specific
  const handler = {} as typeof import("../../../src/app/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/employees/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/employees/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../../src/app/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/employees/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/employees/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/baseline-sheet/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/baseline-sheet/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/baseline-sheet/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/baseline-sheet/data-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/baseline-sheet/data-table">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/baseline-sheet/data-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/baseline-sheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/baseline-sheet">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/baseline-sheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/daily-routines/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/daily-routines/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/daily-routines/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/daily-routines/data-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/daily-routines/data-table">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/daily-routines/data-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/daily-routines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/daily-routines">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/daily-routines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/mass-trial/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/mass-trial/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/mass-trial/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/mass-trial/data-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/mass-trial/data-table">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/mass-trial/data-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/mass-trial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/mass-trial">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/mass-trial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/transaction-sheet/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/transaction-sheet/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/transaction-sheet/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/transaction-sheet/[id]/view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/transaction-sheet/[id]/view">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/transaction-sheet/[id]/view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/transaction-sheet/data-table/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/transaction-sheet/data-table">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/transaction-sheet/data-table/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forms/transaction-sheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forms/transaction-sheet">> = Specific
  const handler = {} as typeof import("../../../src/app/forms/transaction-sheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/client-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/client-services">> = Specific
  const handler = {} as typeof import("../../../src/app/services/client-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/list">> = Specific
  const handler = {} as typeof import("../../../src/app/services/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/session-summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-summary">> = Specific
  const handler = {} as typeof import("../../../src/app/session-summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
